export const VESSEL_SIZE_MULTIPLIER = 1.15 * 1.1;
export const PAPER_SHIP_SCALE = 0.9 * VESSEL_SIZE_MULTIPLIER;
export const PAPER_PLANE_SCALE = 0.86 * VESSEL_SIZE_MULTIPLIER;
export const PAPER_SHIP_RADIUS = 0.82 * VESSEL_SIZE_MULTIPLIER;
export const PAPER_PLANE_RADIUS = VESSEL_SIZE_MULTIPLIER;
export const PLANE_APRON_ROW_SPACING = 2;
export const PLANE_APRON_COLUMN_SPACING = 2.2;
